<a href="https://colab.research.google.com/github/rim-yu/procam-calibration/blob/master/Copy_of_cameraCalibrationCodeReview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
cd /content/drive/"My Drive"/danbi-project/images

/content/drive/My Drive/danbi-project/images


In [0]:
pwd

'/content/drive/My Drive/danbi-project/images'

In [10]:
ls

 calibration_matrix.yaml  'image (16).JPG'  'image (22).JPG'  'image (5).JPG'
'image (10).JPG'          'image (17).JPG'  'image (23).JPG'  'image (6).JPG'
'image (11).JPG'          'image (18).JPG'  'image (24).JPG'  'image (7).JPG'
'image (12).JPG'          'image (19).JPG'  'image (25).JPG'  'image (8).JPG'
'image (13).JPG'          'image (1).JPG'   'image (2).JPG'   'image (9).JPG'
'image (14).JPG'          'image (20).JPG'  'image (3).JPG'
'image (15).JPG'          'image (21).JPG'  'image (4).JPG'


In [0]:
import numpy as np
import cv2
import glob
import yaml
import pathlib
from matplotlib import pyplot as plt 

# termination criteria 종료 기준. 
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((10*7, 3), np.float32)
objp[:,:2] = np.mgrid[0:10,0:7].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
# 패턴 검출을 통해 객체 지점(objpoints)와 이미지 지점(imgpoints)를 파악함. 
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
 
images = glob.glob('image *')
# images = glob.glob("graycode_*")
# path = 'results'
# pathlib.Path(path).mkdir(parents=True, exist_ok=True) 

In [0]:
from google.colab.patches import cv2_imshow

In [11]:
found = 0

for fname in images:  # Here, 10 can be changed to whatever number you like to choose
    img = cv2.imread(fname) # Capture frame-by-frame
    print(fname)
    #print(images[im_i])
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Find the chess board corners 
    # 체스보드의 패턴을 찾기 위해 cv2.findChessboardCorners() 함수를 사용한다. 
    # 이 함수는 코너 지점과 패턴이 발견되었는지 여부를 반환한다. 
    ret, corners = cv2.findChessboardCorners(gray, (10, 7), None)
    # If found, add object points, image points (after refining them)
    if ret == True: # 코너를 발견함. 
        objpoints.append(objp)   # Certainly, every loop objp is the same, in 3D.
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria) # 정확도를 높힘. 
        imgpoints.append(corners2)
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (10,7), corners2, ret) # 결과를 그림. 
        found += 1
        # cv2_imshow(img) # -> colab에서 사용하기 힘든 함수라 함. 
        # cv2.waitKey(500)
        # plt.figure(figsize=(30, 30))
        # plt.imshow(img)
        # plt.axis("off")
        # plt.show()
        # if you want to save images with detected corners 
        # uncomment following 2 lines and lines 5, 18 and 19
        # image_name = path + '/calibresult' + str(found) + '.png'
        # cv2.imwrite(image_name, img)
    
print("Number of images used for calibration: ", found)

image (1).JPG
image (2).JPG
image (3).JPG
image (4).JPG
image (5).JPG
image (6).JPG
image (7).JPG
image (8).JPG
image (9).JPG
image (10).JPG
image (11).JPG
image (12).JPG
image (13).JPG
image (14).JPG
image (15).JPG
image (16).JPG
image (17).JPG
image (18).JPG
image (19).JPG
image (20).JPG
image (21).JPG
image (22).JPG
image (23).JPG
image (24).JPG
image (25).JPG
Number of images used for calibration:  25


In [0]:
len(imgpoints)

48

In [0]:
# When everything done, release the capture
# cap.release()
cv2.destroyAllWindows()

# calibration
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# transform the matrix and distortion coefficients to writable lists
data = {'camera_matrix': np.asarray(mtx).tolist(),
        'dist_coeff': np.asarray(dist).tolist()}

# and save it to a file
with open("calibration_matrix.yaml", "w") as f:
    yaml.dump(data, f)

# done

In [13]:
print("RMS : ", ret)

RMS :  1.0503117463077551


In [0]:
np.asarray(mtx).tolist()

[[2111.8492406740324, 0.0, 1211.2940341075587],
 [0.0, 2056.731484626631, 883.6371360843018],
 [0.0, 0.0, 1.0]]

In [0]:
def printNumpyWithIndent(tar, indentchar):
    print(indentchar + str(tar).replace('\n', '\n' + indentchar))  

In [16]:
rvecs[2] # image(3)가 제일 평평함. 
cam_rotation_matrix = np.zeros(shape=(3, 3))
cv2.Rodrigues(rvecs[2], cam_rotation_matrix) 

print('  cam_rvecs_image(3) :')
printNumpyWithIndent(cam_rotation_matrix, '    ')

  cam_rvecs_image(3) :
    [[ 0.99996346 -0.0082431  -0.00226561]
     [ 0.00841565  0.90260298  0.43039172]
     [-0.00150281 -0.43039506  0.90263937]]


In [17]:
tvecs[2]

array([[-3.09891127],
       [-5.08157722],
       [30.73382527]])

**block size : default**

camera_matrix:

[[2111.8492406740324, 0.0, 1211.2940341075587]

[0.0, 2056.731484626631, 883.6371360843018]

[0.0, 0.0, 1.0]]

dist_coeff:

[[-0.4089409417093742, 2.4885790421166716, 0.043070452804298824, -0.0007310370007457026, -12.445596563012291]]

In [18]:
found = 0

for fname in images:  # Here, 10 can be changed to whatever number you like to choose
    img = cv2.imread(fname) # Capture frame-by-frame
    #print(images[im_i])
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Find the chess board corners 
    # 체스보드의 패턴을 찾기 위해 cv2.findChessboardCorners() 함수를 사용한다. 
    # 이 함수는 코너 지점과 패턴이 발견되었는지 여부를 반환한다. 
    ret, corners = cv2.findChessboardCorners(gray, (10, 7), None)
    # If found, add object points, image points (after refining them)
    if ret == True: # 코너를 발견함. 
        objpoints.append(objp)   # Certainly, every loop objp is the same, in 3D.
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria) # 정확도를 높힘. 
        imgpoints.append(corners2)
        # Draw and display the corners
        # img = cv2.drawChessboardCorners(img, (10,7), corners2, ret) # 결과를 그림. 
        found += 1
        # cv2.imshow('img', img) -> colab에서 사용하기 힘든 함수라 함. 
        # cv2.waitKey(500)
        # if you want to save images with detected corners 
        # uncomment following 2 lines and lines 5, 18 and 19
        # image_name = path + '/calibresult' + str(found) + '.png'
        # cv2.imwrite(image_name, img)

objpoints = [ num * 68 for num in objpoints ] # block size : 68 mm 
print("Number of images used for calibration: ", found)

Number of images used for calibration:  25


In [0]:
# When everything done, release the capture
# cap.release()
cv2.destroyAllWindows()

# calibration
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# transform the matrix and distortion coefficients to writable lists
data = {'camera_matrix': np.asarray(mtx).tolist(),
        'dist_coeff': np.asarray(dist).tolist()}

# and save it to a file
with open("calibration_matrix.yaml", "w") as f:
    yaml.dump(data, f)

# done

In [0]:
print("RMS : ", ret)

RMS :  1.0503117463082716


In [0]:
np.asarray(mtx).tolist()

[[2111.8492406992, 0.0, 1211.294034109914],
 [0.0, 2056.7314846421655, 883.6371360622597],
 [0.0, 0.0, 1.0]]

In [22]:
rvecs[2] # image(3)가 제일 평평함. 
cam_rotation_matrix = np.zeros(shape=(3, 3))
cv2.Rodrigues(rvecs[2], cam_rotation_matrix) 

print('  cam_rvecs_image(3) :')
printNumpyWithIndent(cam_rotation_matrix, '    ')

  cam_rvecs_image(3) :
    [[ 0.99996346 -0.0082431  -0.00226561]
     [ 0.00841565  0.90260298  0.43039172]
     [-0.00150281 -0.43039506  0.90263937]]


In [23]:
tvecs[2]

array([[-210.72596642],
       [-345.54725066],
       [2089.90011831]])

**block size : 6.8 mm**

camera_matrix:

[[2111.8492406992, 0.0, 1211.294034109914]

[0.0, 2056.7314846421655, 883.6371360622597]

[0.0, 0.0, 1.0]]

dist_coeff:

[[-0.40894094173114914, 2.4885790426860726, 0.04307045280817715, -0.0007310370007799288,  -12.445596567134269]]